const dishes = [
  { name: 'Escondidinho de Carne', category: 'Carne bovina', filter: 'carne', description: 'Batata inglesa, patinho moído e especiarias.', price: 22.90, image: 'menu/beef-escondidinho.jpg' },
  { name: 'Panqueca de Carne', category: 'Carne bovina', filter: 'carne', description: 'Massa leve sem lactose, patinho moído, queijo e molho de tomate artesanal.', price: 22.90, image: 'menu/beef-panqueca.jpg' },
  { name: 'Massa Integral à Bolonhesa', category: 'Carne bovina', filter: 'carne', description: 'Penne ou espaguete integral, molho de tomate artesanal e patinho moído.', price: 24.90, image: 'menu/beef-bolonhesa.jpg' },
  { name: 'Massa Integral com Polpetone Recheado', category: 'Carne bovina', filter: 'carne', description: 'Penne ou espaguete integral, molho de tomate artesanal e polpetone de patinho recheado com queijo.', price: 24.90, image: 'menu/beef-polpetone.jpg' },
  { name: 'Brasileirinho de Carne', category: 'Carne bovina', filter: 'carne', description: 'Arroz branco, feijão preto, patinho moído e mix de legumes.', price: 24.90, image: 'menu/beef-brasileirinho.jpg' },
  { name: 'Jardineira', category: 'Carne bovina', filter: 'carne', description: 'Patinho em cubos, mix de legumes ensopados, molho artesanal e arroz branco.', price: 24.90, image: 'menu/beef-jardineira.jpg' },
  { name: 'Escondidinho de Frango', category: 'Frango', filter: 'frango', description: 'Batata inglesa e peito de frango desfiado.', price: 21.90, image: 'menu/chicken-escondidinho.jpg' },
  { name: 'Panqueca de Frango', category: 'Frango', filter: 'frango', description: 'Massa leve sem lactose, frango desfiado, molho de tomate artesanal e queijo.', price: 21.90, image: 'menu/chicken-panqueca.jpg' },
  { name: 'Isca de Frango', category: 'Frango', filter: 'frango', description: 'Arroz integral, iscas de frango ao molho artesanal e mix de legumes.', price: 23.90, image: 'menu/chicken-isca.jpg' },
  { name: 'Arroz Cremoso', category: 'Frango', filter: 'frango', description: 'Arroz, frango, milho, ervilha, cenoura, queijo e molho artesanal.', price: 24.90, image: 'menu/chicken-arroz-cremoso.jpg' },
  { name: 'Brasileirinho de Frango', category: 'Frango', filter: 'frango', description: 'Arroz branco, feijão preto, frango grelhado e mix de legumes.', price: 23.90, image: 'menu/chicken-brasileirinho.jpg' },
  { name: 'Peixe Assado', category: 'Peixes', filter: 'peixe', description: 'Filé de peixe sazonal, arroz integral e mix de legumes.', price: 24.90, image: 'menu/fish-assado.jpg' },
  { name: 'Peixe Grelhado', category: 'Peixes', filter: 'peixe', description: 'Filé de peixe sazonal, arroz de brócolis e mix de legumes.', price: 24.90, image: 'menu/fish-grelhado.jpg' },
  { name: 'Churrasquinho', category: 'Especial', filter: 'especial', description: 'Filé de frango, alcatra e linguiça grelhados, acompanhados de arroz branco, feijão e farofa de alho com tomilho.', price: 24.90, image: 'menu/special-churrasquinho.jpg' },
  { name: 'Creme de Moranga', category: 'Cremes', filter: 'cremes', description: 'Camarão, abóbora, creme de leite, molho artesanal e azeite.', price: 24.90, image: 'menu/cream-moranga-real.jpeg' },
  { name: 'Creme Verde', category: 'Cremes', filter: 'cremes', description: 'Mix de legumes verdes, frango desfiado e base de couve-flor.', price: 21.90, image: 'menu/cream-verde-real.jpeg' },
  { name: 'Creme da Alice (Vegano)', category: 'Cremes', filter: 'cremes', description: 'Abóbora com mix de cogumelos.', price: 22.90, image: 'menu/cream-alice-vegan.JPG' },
  { name: 'Creme da Roça', category: 'Cremes', filter: 'cremes', description: 'Milho, frango e queijo.', price: 21.90, image: 'menu/cream-roca-real.jpeg' }
];
const MINIMUM_ORDER = 50, DELIVERY_FEE = 10, WHATSAPP_BUSINESS_NUMBER = '5521977161757';
let query = '', activeCategory = 'todos', cart = [], discountState = { cpf: '', rate: 0, label: '' }, discountOrderId = null;
const money = value => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const products = document.querySelector('#products');
function renderProducts() { const selected = dishes.filter(dish => (activeCategory === 'todos' || dish.filter === activeCategory) && `${dish.name} ${dish.description}`.toLowerCase().includes(query)); products.innerHTML = selected.map(dish => `<article class="product"><div class="product-image ${dish.image ? '' : 'product-art'}">${dish.image ? `<img src="assets/${dish.image}" alt="${dish.name}">` : '<span>Cremes<br />da Luz</span>'}</div><span class="product-tag">${dish.category}</span><h3>${dish.name}</h3><p>${dish.description}</p><div class="product-bottom"><span class="price">${money(dish.price)}</span><button class="add" data-index="${dishes.indexOf(dish)}" aria-label="Adicionar ${dish.name}">+</button></div></article>`).join(''); document.querySelector('#empty').style.display = selected.length ? 'none' : 'block'; }
function resetDiscountReservation() { discountOrderId = null; }
function renderCart() { const box = document.querySelector('#cartItems'), subtotal = cart.reduce((sum, item) => sum + item.price, 0), delivery = cart.length ? DELIVERY_FEE : 0, discount = subtotal * ((discountState.rate || 0) / 100), total = subtotal + delivery - discount, remaining = Math.max(0, MINIMUM_ORDER - subtotal), grouped = cart.reduce((items, item, index) => { const key = `${item.name}|${item.price}`; items[key] = items[key] || { ...item, quantity: 0, index }; items[key].quantity += 1; return items; }, {}); document.querySelector('#cartCount').textContent = cart.length; document.querySelector('#cartSubtotal').textContent = money(subtotal); document.querySelector('#deliveryFee').textContent = money(delivery); document.querySelector('#cartTotal').textContent = money(total); document.querySelector('#cartDiscountRow').hidden = !(discount > 0); document.querySelector('#cartDiscountLabel').textContent = discountState.label || 'Desconto'; document.querySelector('#cartDiscountValue').textContent = `- ${money(discount)}`; document.querySelector('#minimumNotice').textContent = subtotal >= MINIMUM_ORDER ? 'Pedido mínimo atingido ✓' : `Faltam ${money(remaining)} para o pedido mínimo de ${money(MINIMUM_ORDER)}.`; document.querySelector('#minimumNotice').classList.toggle('met', subtotal >= MINIMUM_ORDER); box.innerHTML = cart.length ? Object.values(grouped).map(item => `<div class="cart-line"><div><h3>${item.name}</h3><p>${money(item.price)}</p><button data-cart-action="remove" data-cart-index="${item.index}">Remover</button></div><div class="cart-quantity"><button type="button" data-cart-action="decrease" data-cart-index="${item.index}" aria-label="Diminuir ${item.name}">−</button><strong>${item.quantity}×</strong><button type="button" data-cart-action="increase" data-cart-index="${item.index}" aria-label="Aumentar ${item.name}">+</button></div></div>`).join('') : '<p class="cart-empty">Sua sacola está vazia.</p>'; }
function toggleCart(show) { document.querySelector('#cart').classList.toggle('open', show); document.querySelector('#overlay').classList.toggle('open', show); }
document.querySelector('.menu-filters').addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; activeCategory = button.dataset.category; document.querySelectorAll('.menu-filters button').forEach(item => item.classList.toggle('active', item === button)); renderProducts(); });
products.addEventListener('click', event => { const button = event.target.closest('.add'); if (!button) return; cart.push(dishes[Number(button.dataset.index)]); resetDiscountReservation(); renderCart(); toggleCart(true); });
document.querySelector('#cartItems').addEventListener('click', event => { const button = event.target.closest('[data-cart-action]'); if (!button) return; const index = Number(button.dataset.cartIndex), item = cart[index]; if (!item) return; if (button.dataset.cartAction === 'increase') cart.push(item); if (button.dataset.cartAction === 'decrease') cart.splice(index, 1); if (button.dataset.cartAction === 'remove') cart = cart.filter(product => product.name !== item.name || product.price !== item.price); resetDiscountReservation(); renderCart(); });
document.querySelector('#cartButton').onclick = () => toggleCart(true); document.querySelector('#closeCart').onclick = () => toggleCart(false); document.querySelector('#overlay').onclick = () => toggleCart(false); document.querySelector('#continueShopping').onclick = () => { toggleCart(false); document.querySelector('#cardapio').scrollIntoView({ behavior: 'smooth', block: 'start' }); }; document.querySelector('#searchInput').addEventListener('input', event => { query = event.target.value.toLowerCase().trim(); renderProducts(); }); document.querySelector('#searchToggle').onclick = () => { document.querySelector('#searchBox').scrollIntoView({ behavior: 'smooth', block: 'center' }); document.querySelector('#searchInput').focus(); }; renderProducts(); renderCart();

const comboChoices = dishes.map(dish => ({ name: dish.name, kind: dish.filter === 'cremes' ? 'creme' : 'marmita' }));
let comboType = 'mix', comboSelection = [];
const comboOptions = document.querySelector('#comboOptions'), comboCount = document.querySelector('#comboCount'), comboInstruction = document.querySelector('#comboInstruction'), comboPrice = document.querySelector('#comboPrice'), comboHint = document.querySelector('#comboHint'), addCombo = document.querySelector('#addCombo');
function comboRules() { if (comboType === 'mix') return { marmita: 8, creme: 2, price: 149.90, label: '8 marmitas de 400g e 2 cremes de 300g' }; if (comboType === 'marmitas') return { marmita: 10, creme: 0, price: 169.90, label: '10 marmitas de 400g' }; return { marmita: 0, creme: 10, price: 129.90, label: '10 cremes de 300g' }; }
function renderCombo() { const rules = comboRules(), visible = comboType === 'mix' ? comboChoices : comboChoices.filter(choice => choice.kind === (comboType === 'marmitas' ? 'marmita' : 'creme')), marmitas = comboSelection.filter(choice => choice.kind === 'marmita').length, cremes = comboSelection.filter(choice => choice.kind === 'creme').length, complete = marmitas === rules.marmita && cremes === rules.creme; comboOptions.innerHTML = visible.map(choice => { const count = comboSelection.filter(item => item === choice).length, sameKind = choice.kind === 'marmita' ? marmitas : cremes, max = rules[choice.kind], index = comboChoices.indexOf(choice); return `<div class="combo-option ${count ? 'selected' : ''}"><span><small>${choice.kind === 'marmita' ? 'marmita · 400g' : 'creme · 300g'}</small><strong>${choice.name}</strong></span><div class="combo-quantity"><button type="button" data-action="decrease" data-choice="${index}" aria-label="Diminuir ${choice.name}" ${count === 0 ? 'disabled' : ''}>−</button><b>${count}</b><button type="button" data-action="increase" data-choice="${index}" aria-label="Aumentar ${choice.name}" ${sameKind >= max ? 'disabled' : ''}>+</button></div></div>`; }).join(''); comboCount.textContent = rules.marmita && rules.creme ? `${marmitas} de 8 marmitas · ${cremes} de 2 cremes` : rules.marmita ? `${marmitas} de 10 marmitas` : `${cremes} de 10 cremes`; comboInstruction.textContent = `Escolha ${rules.label}`; comboPrice.textContent = money(rules.price); comboHint.textContent = complete ? 'Tudo certo! Seu combo está pronto para ir à sacola.' : `Faltam ${Math.max(0, rules.marmita - marmitas) + Math.max(0, rules.creme - cremes)} escolhas para completar.`; addCombo.disabled = !complete; }
document.querySelectorAll('.combo-tab').forEach(tab => tab.addEventListener('click', () => { comboType = tab.dataset.combo; comboSelection = []; document.querySelectorAll('.combo-tab').forEach(button => button.classList.toggle('active', button === tab)); renderCombo(); }));
comboOptions.addEventListener('click', event => { const button = event.target.closest('[data-action]'); if (!button) return; const choice = comboChoices[Number(button.dataset.choice)], rules = comboRules(); if (button.dataset.action === 'increase') { const sameKind = comboSelection.filter(item => item.kind === choice.kind).length; if (sameKind < rules[choice.kind]) comboSelection.push(choice); } else { const index = comboSelection.lastIndexOf(choice); if (index !== -1) comboSelection.splice(index, 1); } renderCombo(); });
document.querySelector('#resetCombo').addEventListener('click', () => { comboSelection = []; renderCombo(); }); addCombo.addEventListener('click', () => { const rules = comboRules(); cart.push({ name: `Combo personalizado: ${rules.label}`, price: rules.price }); resetDiscountReservation(); renderCart(); toggleCart(true); }); renderCombo();

const accountStorageKey = 'luz-gastronomia-customer';
const accountModal = document.querySelector('#accountModal');
const accountButton = document.querySelector('#accountButton');
const accountForms = { identify: document.querySelector('#identifyForm'), profile: document.querySelector('#profileForm'), address: document.querySelector('#addressForm'), success: document.querySelector('#accountSuccess') };
let customerDraft = null;
function savedCustomer() { try { return JSON.parse(localStorage.getItem(accountStorageKey)); } catch { return null; } }
async function requestDiscount(customer, action = 'quote') { const cpf = String(customer?.cpf || '').replace(/\D/g, ''); if (!cpf) return { rate: 0, label: '' }; if (action === 'reserve' && !discountOrderId) discountOrderId = crypto.randomUUID(); const response = await fetch('/.netlify/functions/discount', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ cpf, action, orderId: action === 'reserve' ? discountOrderId : undefined }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível consultar o desconto.'); discountState = { cpf, rate: Number(data.rate) || 0, label: data.label || '' }; return discountState; }
async function refreshDiscountQuote() { const customer = savedCustomer(); try { if (!customer?.cpf) { discountState = { cpf: '', rate: 0, label: '' }; } else { await requestDiscount(customer); } } catch { discountState = { cpf: '', rate: 0, label: '' }; } renderCart(); }
function updateAccountButton() { const customer = savedCustomer(); document.querySelector('#accountLabel').textContent = customer?.name ? customer.name.split(' ')[0] : 'Minha conta'; }
function setProgress(step) { const items = document.querySelectorAll('.account-progress i'); items.forEach((item, index) => item.classList.toggle('active', index <= step)); }
function showAccountStep(step) { Object.values(accountForms).forEach(form => form.hidden = true); accountForms[step].hidden = false; setProgress(step === 'identify' ? 0 : step === 'profile' ? 1 : 2); }
function setIdentityFields(customer) { const fields = [document.querySelector('#customerName'), document.querySelector('#profileEmail'), document.querySelector('#customerCpf')]; fields.forEach(field => { const canEdit = field.id === 'customerCpf' ? !customer?.cpf : !customer; field.readOnly = !canEdit; field.setAttribute('aria-readonly', String(!canEdit)); }); document.querySelector('#identityLockNote').hidden = !customer; }
function fillAccountForms(customer) { if (!customer) return; document.querySelector('#customerEmail').value = customer.email || ''; document.querySelector('#customerPhone').value = customer.phone || ''; document.querySelector('#profileEmail').value = customer.email || ''; document.querySelector('#profilePhone').value = customer.phone || ''; document.querySelector('#customerName').value = customer.name || ''; document.querySelector('#customerCpf').value = customer.cpf || ''; document.querySelector('#marketingConsent').checked = Boolean(customer.marketing); const address = customer.address || {}; Object.entries(address).forEach(([key, value]) => { const field = accountForms.address.elements.namedItem(key); if (field) field.value = value || ''; }); }
function openAccount(step = 'identify') { const customer = savedCustomer(); customerDraft = customer ? { ...customer } : null; setIdentityFields(customer); fillAccountForms(customer); accountModal.hidden = false; showAccountStep(step); }
function closeAccount() { accountModal.hidden = true; }
accountButton.addEventListener('click', () => openAccount(savedCustomer() ? 'profile' : 'identify'));
document.querySelector('#closeAccount').addEventListener('click', closeAccount);
accountModal.addEventListener('click', event => { if (event.target === accountModal) closeAccount(); });
accountForms.identify.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(accountForms.identify)); customerDraft = { ...(savedCustomer() || {}), ...data }; document.querySelector('#profileEmail').value = data.email; document.querySelector('#profilePhone').value = data.phone; showAccountStep('profile'); });
accountForms.profile.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(accountForms.profile)); customerDraft = { ...customerDraft, ...data, marketing: document.querySelector('#marketingConsent').checked }; showAccountStep('address'); });
accountForms.address.addEventListener('submit', event => { event.preventDefault(); const address = Object.fromEntries(new FormData(accountForms.address)); const customer = { ...customerDraft, address }; localStorage.setItem(accountStorageKey, JSON.stringify(customer)); customerDraft = customer; updateAccountButton(); refreshDiscountQuote(); showAccountStep('success'); });
const customerZip = document.querySelector('#customerZip'), zipLookupStatus = document.querySelector('#zipLookupStatus');
customerZip.addEventListener('input', () => { const zip = customerZip.value.replace(/\D/g, '').slice(0, 8); customerZip.value = zip.replace(/(\d{5})(\d)/, '$1-$2'); if (zip.length !== 8) { zipLookupStatus.textContent = 'Digite os 8 números do CEP.'; return; } zipLookupStatus.textContent = 'Buscando endereço...'; fetch(`https://viacep.com.br/ws/${zip}/json/`).then(response => { if (!response.ok) throw new Error(); return response.json(); }).then(data => { if (data.erro) throw new Error(); accountForms.address.elements.street.value = data.logradouro || ''; accountForms.address.elements.neighborhood.value = data.bairro || ''; zipLookupStatus.textContent = data.logradouro && data.bairro ? 'Endereço preenchido. Complete apenas o número.' : 'CEP encontrado. Complete os campos que estiverem em branco.'; if (!data.logradouro) { accountForms.address.elements.street.readOnly = false; accountForms.address.elements.street.placeholder = 'Informe o logradouro'; } if (!data.bairro) { accountForms.address.elements.neighborhood.readOnly = false; accountForms.address.elements.neighborhood.placeholder = 'Informe o bairro'; } accountForms.address.elements.number.focus(); }).catch(() => { zipLookupStatus.textContent = 'Não foi possível localizar este CEP. Confira os números.'; accountForms.address.elements.street.value = ''; accountForms.address.elements.neighborhood.value = ''; }); });
document.querySelector('#accountDone').addEventListener('click', () => { closeAccount(); toggleCart(true); refreshDiscountQuote(); });
function checkoutWhatsAppMessage(customer, subtotal, discount) { const quantities = cart.reduce((items, item) => { const key = `${item.name}|${item.price}`; items[key] = items[key] || { ...item, quantity: 0 }; items[key].quantity += 1; return items; }, {}); const items = Object.values(quantities).map(item => `• ${item.quantity}x ${item.name} — ${money(item.price * item.quantity)}`); const address = customer.address, discountValue = subtotal * ((discount.rate || 0) / 100), addressLine = [address.street, address.number, address.complement].filter(Boolean).join(', '); return ['Olá, Luz Gastronomia! Gostaria de finalizar este pedido.', '', '*ITENS DO PEDIDO*', ...items, '', `*Subtotal:* ${money(subtotal)}`, discountValue ? `*${discount.label}:* - ${money(discountValue)}` : '', `*Taxa de entrega:* ${money(DELIVERY_FEE)}`, `*Total:* ${money(subtotal + DELIVERY_FEE - discountValue)}`, '', '*DADOS PARA ENTREGA*', `Nome: ${customer.name || 'Não informado'}`, `CPF: ${customer.cpf || 'Não informado'}`, `Celular: ${customer.phone || 'Não informado'}`, customer.email ? `E-mail: ${customer.email}` : '', `Endereço: ${addressLine}`, `Bairro: ${address.neighborhood}`, address.zip ? `CEP: ${address.zip}` : '', `Referência: ${address.reference}`, '', 'Aguardo as instruções para pagamento por Pix, crédito ou débito.'].filter(Boolean).join('\n'); }
document.querySelector('.checkout').addEventListener('click', async event => { const subtotal = cart.reduce((sum, item) => sum + item.price, 0); if (subtotal < MINIMUM_ORDER) { alert(`O pedido mínimo é de ${money(MINIMUM_ORDER)}. Adicione mais ${money(MINIMUM_ORDER - subtotal)} em produtos para continuar.`); return; } const customer = savedCustomer(); if (!customer) { toggleCart(false); openAccount('identify'); return; } if (!customer.cpf || !customer.address?.zip || !customer.address?.street || !customer.address?.number || !customer.address?.neighborhood) { toggleCart(false); openAccount(!customer.cpf ? 'profile' : 'address'); return; } const button = event.currentTarget, whatsapp = window.open('', '_blank'); button.disabled = true; try { const discount = await requestDiscount(customer, 'reserve'); renderCart(); const message = checkoutWhatsAppMessage(customer, subtotal, discount); const url = `https://wa.me/${WHATSAPP_BUSINESS_NUMBER}?text=${encodeURIComponent(message)}`; if (whatsapp) whatsapp.location.href = url; else window.location.href = url; } catch (error) { if (whatsapp) whatsapp.close(); alert(error.message || 'Não foi possível confirmar o desconto. Tente novamente.'); } finally { button.disabled = false; } });
updateAccountButton(); refreshDiscountQuote();

const menuToggle = document.querySelector('#menuToggle');
const mainNav = document.querySelector('#mainNav');
menuToggle.addEventListener('click', () => { const isOpen = mainNav.classList.toggle('open'); menuToggle.classList.toggle('open', isOpen); menuToggle.setAttribute('aria-expanded', String(isOpen)); });
mainNav.addEventListener('click', event => { if (event.target.matches('a')) { mainNav.classList.remove('open'); menuToggle.classList.remove('open'); menuToggle.setAttribute('aria-expanded', 'false'); } });

const motionTargets = document.querySelectorAll('.benefits article, .section-heading, .menu-collection, .combo-intro, .combo-shell, .preparation-intro, .prep-card, .prep-bottom, .story-photo, .story-content, .apron > div, .apron > img, footer > div');
motionTargets.forEach(target => target.classList.add('animate-on-scroll'));
if ('IntersectionObserver' in window) { const motionObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('motion-visible'); motionObserver.unobserve(entry.target); } }), { threshold: 0.12 }); motionTargets.forEach(target => motionObserver.observe(target)); } else { motionTargets.forEach(target => target.classList.add('motion-visible')); }
